### ISSUE TITLE
training cost

### ISSUE THREAD

**Issue by twangnh** [fuqichen1998/SequentialVotingDet#1]
Hi! thanks for the great work! I'm wondering how long does the model train on the two datasets?

**Comment by fuqichen1998** [comment]
Hi, thanks for your interest in our work! With 4 x 2080Ti GPUs, this model typically takes about 1 day to train on the 100DOH dataset and 0.5 days to train on the MECCANO dataset. Finetune with RL will take about extra 6-8 hours on any one of the datasets.
