### ISSUE TITLE
where can I download 100DOH

### ISSUE THREAD

**Issue by lapvision** [fuqichen1998/SequentialVotingDet#2]

**Comment by lapvision** [comment]
The 100DOH dataset can not be downloaded now. Can you share the data ? Thanks!

**Comment by fuqichen1998** [comment]
Hi, thanks for your interest in our work. Unfortunately, as restricted by the dataset license, we can't share the data directly with you. We recommend reporting this issue to Dandan Shan, the person of contact of the 100DOH dataset.

**Comment by lapvision** [comment]
Ok， thanks！

**Comment by fuqichen1998** [comment]
The dataset is online again.
